### ISSUE TITLE
Is there a way to choose custom names for each tree item?

### ISSUE THREAD

**Issue by arturbosch** [TomasMikula/LiveDirsFX#8]
The default option is that the whole path name is displayed within the tree view. I just want to display the filename (path.fileName). I did not yet a way to do this, is there one?

**Comment by TomasMikula** [comment]
Yes, you can use [TreeView.setCellFactory](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/TreeView.html#setCellFactory-javafx.util.Callback-) to customize the appearance of the tree cells.

**Comment by arturbosch** [comment]
Thx :)
